var isPad = navigator.userAgent.match(/iPhone|Linux|Android|iPad|iPod|ios|iOS|Windows Phone|Phone|WebOS/i) != null;
document.writeln("<!-- Start topbar -->");
document.writeln("<div class=\"topbar\" style=\"postion:absolute;border-style:none;z-index:9999\">");
document.writeln("<div class=\"content\" style=\"postion:absolute;border-style:none;z-index:9999\">");
document.writeln("<ul class=\"menus fl\">");
document.writeln("<a><b class=\"fl\"><\/b><\/a>");
document.writeln("<a><b class=\"fl\"><\/b><\/a>");
document.writeln("<a><b class=\"fl\"><\/b><\/a>");
document.writeln("<a><b class=\"fl\"><\/b><\/a>");
document.writeln("<a><b class=\"fl\"><\/b><\/a>");
document.writeln("<a><b class=\"fl\"><\/b><\/a>");
document.writeln("<a><b class=\"fl\"><\/b><\/a>");
document.writeln("<a><b class=\"fl\"><\/b><\/a>");
document.writeln("<li class=\"menu hoverhandler\">");
document.writeln("<a href=\"javascript:;\" class=\"link\" title=\"首页\"><span class=\"fl\">首页<\/span><b class=\"fl\"><\/b><\/a>");
document.writeln("<ul class=\"dropdownmenu fillet\">");
document.writeln("<b><\/b><br><\/br>");
document.writeln("<li><a  href=\"../?&f=\" rel=\"dropmenu1\" class=\"viemo\" title=\"首页\" >首页<\/a><\/li>");
document.writeln("<li><a  href=\"../?s=2&f=\" rel=\"dropmenu1\" class=\"viemo\" title=\"央视\" >央视<\/a><\/li>");
document.writeln("<li><a  href=\"../?s=1&f=\" rel=\"dropmenu1\" class=\"viemo\" title=\"卫视\" >卫视<\/a><\/li>");
document.writeln("<li><a  href=\"../?s=3&f=\" rel=\"dropmenu1\" class=\"viemo\" title=\"地方台\" >地方台<\/a><\/li>");
document.writeln("<li><a  href=\"../?s=4&f=\" rel=\"dropmenu1\" class=\"viemo\" title=\"测试\" >测试<\/a><\/li>");
if(isPad) { 
document.writeln("<li><a  href=\"../?&s=skso&p=&a=&t=&u=&w=\" class=\"viemo\">搜酷<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=cnso&p=&a=&t=&u=&w=\" class=\"viemo\">cn搜<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=byso&p=&a=&t=&u=&w=\" class=\"viemo\">bing搜<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=sgwso&p=&a=1&t=&u=&w=\" class=\"viemo\">搜狗w<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=sgmso&p=&a=&t=4&u=&w=\" class=\"viemo\">搜狗m<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=sgvso&a=&t=&u=&p=&w=\" class=\"viemo\">搜狗v<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=skmso&p=&a=&t=&u=&w=\" class=\"viemo\">搜酷m<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=qqso&t=&u=&p=&w=\" class=\"viemo\">QQ搜<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=cnso&p=&a=&t=&u=&w=\" class=\"viemo\">cn搜索<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=cnsso&t=&u=&p=&w=\" class=\"viemo\">cn电视剧<\/a><\/li>");
document.writeln("<li><a  href=\"../xw\/xww.php?&m=&s=&u=&t=&p=&w=\" class=\"viemo\">实时新闻<\/a><\/li><\/br>");
} else {
document.writeln("<li><a  href=\"../?&s=skso&p=&a=&t=&u=&w=\" class=\"viemo\">搜酷<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=byso&p=&a=&t=&u=&w=\" class=\"viemo\">bing搜<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=sgwso&p=&a=1&t=&u=&w=\" class=\"viemo\">搜狗w<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=sgmso&p=&a=&t=4&u=&w=\" class=\"viemo\">搜狗m<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=sgvso&a=&t=&u=&p=&w=\" class=\"viemo\">搜狗v<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=skmso&p=&a=&t=&u=&w=\" class=\"viemo\">搜酷m<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=qqso&t=&u=&p=&w=\" class=\"viemo\">QQ搜<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=cnso&p=&a=&t=&u=&w=\" class=\"viemo\">cn搜索<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=cnsso&t=&u=&p=&w=\" class=\"viemo\">cn电视剧<\/a><\/li>");
document.writeln("<li><a  href=\"../xw\/zx.php?&m=&s=&u=&t=&p=&w=\" class=\"viemo\">实时资讯<\/a><\/li>");
document.writeln("<li><a  href=\"../xw\/xw.php?&m=&s=&u=&t=&p=&w=\" class=\"viemo\">实时新闻<\/a><\/li>");
}
document.writeln("<\/ul>");
document.writeln("<\/li>");
document.writeln("<li class=\"menu hoverhandler\">");
document.writeln("<a class=\"link \"><b class=\"fl\"><\/b><\/a>");
document.writeln("<li class=\"menu hoverhandler\">");
document.writeln("<a href=\"javascript:;\" class=\"link \"><span class=\"fl\">电影<\/span><b class=\"fl\"><\/b><\/a>");
document.writeln("<ul class=\"dropdownmenu fillet\">");
document.writeln("<b><\/b><br><\/br>");
document.writeln("<li><a  href=\"../?&s=skdy&a=&t=&u=&p=&w=\" class=\"viemo\">全网<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=cnlmmv&t=&u=&p=&w=\" class=\"viemo\">cn栏目<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=mgdy&t=&u=&p=&w=\" class=\"viemo\">芒果<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=qydy&t=&u=&p=&w=\" class=\"viemo\">奇异<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=ykdy&t=&u=&p=&w=\" class=\"viemo\">优酷<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=ykvdy&t=&u=&p=&w=\" class=\"viemo\">优酷v<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=shudy&t=&u=&p=&w=\" class=\"viemo\">搜狐<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=qqdy&t=&u=&p=&w=1\" class=\"viemo\">qq<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=wsdy&t=&u=&p=&w=\" class=\"viemo\">华数<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=ledy&t=&u=&p=&w=\" class=\"viemo\">乐视<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=m163mv&t=&u=&p=&w=1\" class=\"viemo\">163课<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=n360dy&t=&u=&p=&w=\" class=\"viemo\">36mv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=n360dy&t=1&u=&p=&w=\" class=\"viemo\">360电视剧<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=bitv&u=&t=&p=2&w=\" class=\"viemo\">毕哩tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=bitvs0&p=3&a=&u=1&t=4&w=\" class=\"viemo\">毕哩搜索<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=fundy&t=&a=&u=&p=&w=\" class=\"viemo\">风行<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=xiangmv&u=&t=&p=&w=\" class=\"viemo\">相声<\/a><\/li>");
document.writeln("<\/ul>");
document.writeln("<\/li>");
document.writeln("<li class=\"menu hoverhandler\">");
document.writeln("<a class=\"link \"><b class=\"fl\"><\/b><\/a>");
document.writeln("<li class=\"menu hoverhandler\">");
document.writeln("<a href=\"javascript:;\" class=\"link \"><span class=\"fl\">TV<\/span><b class=\"fl\"><\/b><\/a>");
document.writeln("<ul class=\"dropdownmenu fillet\">");
document.writeln("<b><\/b><br><\/br>");
if(isPad) {
document.writeln("<li><a  href=\"../?&s=cctvzb&&a=&u=&t=&p=&w=\" class=\"viemo\">cctv直播<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=qitv&u=&t=&p=&w=\" class=\"viemo\">qitv<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=hytv&a=9&u=&t=&p=&w=\" class=\"viemo\">虎牙tv<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=bilitv&a=&u=&t=&p=14&w=\" class=\"viemo\">毕哩tv<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=bitvs&a=&u=&t=&p=8&w=\" class=\"viemo\">毕哩tv搜<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=qetv&a=&u=&t=&p=3&w=\" class=\"viemo\">企鹅tv<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=kutv&a=&u=&t=&p=3&w=\" class=\"viemo\">酷狗tv<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=bxtv&a=&u=&t=&p=1&w=\" class=\"viemo\">百秀tv<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=kkxtv&a=&u=&t=&p=&w=\" class=\"viemo\">kk秀<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=ttzb&a=3&u=&p=&w=&f=&t=\" class=\"viemo\">头条<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=jstv&u=&t=&p=&w=1\" class=\"viemo\">卫视<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=zgzb&m=&u=&t=&p=&w=\" class=\"viemo\">直播中国<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=zgjqzb&a=&m=&u=&t=&p=2&w=\" class=\"viemo\">直播中国2<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=x1av&a=&u=&t=1&p=2&w=\" class=\"viemo\">最新影片<\/a><\/li>");
} else {
document.writeln("<li><a  href=\"../?&s=cctvzb&a=11&u=&t=&p=&w=\" class=\"viemo\">cctv直播<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=t64tv&u=&t=&p=&w=\" class=\"viemo\">64tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=shhtv&u=&t=&p=&w=\" class=\"viemo\">上海tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=hytv&a=9&u=&t=&p=&w=\" class=\"viemo\">虎牙tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=qetv&a=1&u=&t=&p=3&w=\" class=\"viemo\">企鹅tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=bilitv&a=1&u=&t=&p=14&w=\" class=\"viemo\">毕哩tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=bitvs&a=1&u=&t=&p=8&w=\" class=\"viemo\">毕哩tv搜<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=kutv&a=&u=&t=&p=3&w=\" class=\"viemo\">酷狗tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=ttzb&a=&u=&p=&w=&f=&t=\" class=\"viemo\">头条<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=yytv&a=&u=&t=&p=&w=\" class=\"viemo\">yytv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=hjtv&a=&u=&t=&p=&w=1\" class=\"viemo\">花椒tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=v6tv&a=&u=&t=&p=&w=\" class=\"viemo\">6间房<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=wxtv&a=&u=&t=&p=&w=\" class=\"viemo\">我秀tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=t95tv&a=&u=&t=&p=&w=\" class=\"viemo\">95秀tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=nowtv&a=&u=&t=&p=&w=\" class=\"viemo\">nowtv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=bxtv&a=&u=&t=&p=1&w=\" class=\"viemo\">百秀tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=kkxtv&a=&u=&t=&p=&w=\" class=\"viemo\">kk秀<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=iktv&a=&u=&t=&p=&w=\" class=\"viemo\">映客<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=hmgtv&a=&u=&t=&p=&w=\" class=\"viemo\">芒果tv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=zgzb&a=&m=&u=&t=&p=&w=\" class=\"viemo\">直播中国<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=zgjqzb&a=&m=&u=&t=&p=2&w=\" class=\"viemo\">直播中国2<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=x1av&a=&u=&t=1&p=2&w=\" class=\"viemo\">最新影片<\/a><\/li>");
}
document.writeln("<\/ul>");
document.writeln("<\/li>");
document.writeln("<li class=\"menu hoverhandler\">");
document.writeln("<a class=\"link \"><b class=\"fl\"><\/b><\/a>");
document.writeln("<li class=\"menu hoverhandler\">");
document.writeln("<a href=\"javascript:;\" class=\"link \"><span class=\"fl\">音乐<\/span><b class=\"fl\"><\/b><\/a>");
document.writeln("<ul class=\"dropdownmenu fillet\">");
document.writeln("<b><\/b><br><\/br>");
if(isPad) {
document.writeln("<li><a  href=\"../u.htm?&u=12&f=\" class=\"viemo\">电视剧搜索解析<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=kugso&a=&u=&t=&p=&w=\" class=\"viemo\">酷狗mv<\/a><\/li><\/br>");
document.writeln("<li><a  href=\"../?&s=kugsso&a=&u=&t=&p=&w=\" class=\"viemo\">酷狗搜索<\/a><\/li><\/br>");
} else {
document.writeln("<li><a  href=\"../u.htm?&u=12&f=\" class=\"viemo\">电视剧搜索解析<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=kugso&a=&u=&t=&p=&w=\" class=\"viemo\">酷狗mv<\/a><\/li>");
document.writeln("<li><a  href=\"../?&s=kugsso&a=&u=&t=&p=&w=\" class=\"viemo\">酷狗搜索<\/a><\/li>");
}
document.writeln("<\/ul>");
document.writeln("<\/li>");
document.writeln("<\/div>");
document.writeln("<\/div>");
document.writeln("<\/topbar>");
document.writeln("<!-- End topbar -->")